---
url: https://www.emfink.net 
baseurl: /Recipes
title: Recipes
description:  # leave blank for no description 
last_updated: 10 January 2021

author: Eric M. Fink 
city: Greensboro
state: North Carolina
email: emfink@gmail.com

collections: 
  breads: 
    output: true 
  drinks:
    output: true
  eggs:
    output: true
  grains:
    output: true
  meats:
    output: true
  sauces:
    output: true
  seafoods:
    output: true
  sides:
    output: true
  soups:
    output: true
  sweets:
    output: true


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings

# deployment
host: localhost
port: 4000


markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
include: ['_pages']
exclude: ['Gemfile.lock', .admin]
keep_files: [.admin]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/EricMFink.github.com/

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
