---
url: https://www.emfink.net 
baseurl: /Recipes
title: Recipes
description:  # leave blank for no description 
last_updated: 7 January 2021

author: Eric M. Fink 
city: Greensboro
state: North Carolina
email: emfink@gmail.com

collections: 
  breads: 
    output: true 
  drinks:
    output: true
  eggs:
    output: true
  grains:
    output: true
  meats:
    output: true
  sauces:
    output: true
  seafoods:
    output: true
  sides:
    output: true
  soups:
    output: true
  sweets:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
  
remote_theme: EricMFink/EricMFink.github.io

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
